[package]
name = "core-prop"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.46.0", features = ["lazy"] }
ndarray = { version = "0.16.1", features = ["serde"] }
rand = "0.9.0"